import { useMemo, useState } from 'react';
import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/Components/ui/dialog';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/Components/ui/select';
import { Textarea } from '@/Components/ui/textarea';
import { Checkbox } from '@/Components/ui/checkbox';
import { CalendarDays, CheckCircle2, Clock3, Plus } from 'lucide-react';
import { Laboratory, PaginatedData } from '@/types';

type Booking = { id:number; user_id:number; laboratory: Laboratory; user:{name:string}; supervisor:{id:number;name:string}; start_time:string; end_time:string; purpose:string; status:string; items:Array<{quantity:number; equipment:{id:number;name:string;unit_type:string}}> };
interface Props { bookings:PaginatedData<Booking>; laboratories:Pick<Laboratory,'id'|'name'|'code'>[]; equipment:Array<{id:number;laboratory_id:number;name:string;quantity:number;unit_type:string}>; supervisors:Array<{id:number;name:string}>; can_approve:boolean; booking_view:'student'|'supervisor'|'assistant'|'admin'; summary:{total:number;pending:number;approved:number}; }

export default function Index({ bookings, laboratories, equipment, supervisors, can_approve:canApprove, booking_view:view, summary }:Props) {
 const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Booking|null>(null); const {data,setData,post,processing,reset}=useForm({laboratory_id:'',supervisor_id:'',start_time:'',end_time:'',purpose:'',safety_declared:false,items:[{equipment_inventory_item_id:'',quantity:1}]});
 const currentUserId=usePage().props.auth.user.id;
 const selectable=useMemo(()=>equipment.filter(e=>String(e.laboratory_id)===data.laboratory_id),[equipment,data.laboratory_id]);
 const submit=(e:React.FormEvent)=>{e.preventDefault(); if(editing) router.patch(route('bookings.update',editing.id),{...data,action:'edit'},{onSuccess:()=>{setOpen(false);setEditing(null);reset();}}); else post(route('bookings.store'),{onSuccess:()=>{setOpen(false);reset();}})};
 const edit=(booking:Booking)=>{setEditing(booking);setData({laboratory_id:String(booking.laboratory.id),supervisor_id:String(booking.supervisor.id),start_time:booking.start_time.slice(0,16),end_time:booking.end_time.slice(0,16),purpose:booking.purpose,safety_declared:true,items:booking.items.map(item=>({equipment_inventory_item_id:String(item.equipment.id),quantity:item.quantity}))});setOpen(true);};
 const action=(id:number,action:'approve'|'reject'|'cancel')=>router.patch(route('bookings.update',id),{action});
 const reject=(id:number)=>{const rejection_reason=window.prompt('Enter the reason for rejecting this booking.');if(rejection_reason?.trim())router.patch(route('bookings.update',id),{action:'reject',rejection_reason});};
 const heading={student:'My Bookings',supervisor:'Supervisor Approvals',assistant:'Bookings for My Laboratories',admin:'All Bookings'}[view];
 const sub={student:'Track your requests and create a new booking.',supervisor:'Review requests assigned to you.',assistant:'Approve bookings for laboratories under your responsibility.',admin:'View and manage booking activity across the system.'}[view];
 const canApproveBooking=(booking:Booking)=>canApprove&&((view==='supervisor'&&booking.status==='pending_supervisor')||((view==='assistant'||view==='admin')&&booking.status==='pending_admin'));
 const canRejectBooking=(booking:Booking)=>canApprove&&((view==='supervisor'&&booking.status==='pending_supervisor')||(view==='assistant'&&['pending_supervisor','pending_admin'].includes(booking.status))||(view==='admin'&&booking.status==='pending_admin'));
 return <AuthenticatedLayout header={<div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">{heading}</h2><p className="text-sm text-zinc-500">{sub}</p></div><Button onClick={()=>{setEditing(null);reset();setOpen(true)}}><Plus className="mr-2 h-4 w-4"/>New Booking</Button></div>}><Head title="Bookings"/><div className="mx-auto max-w-7xl space-y-5 p-6">
  <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-zinc-500">Total Bookings</p><p className="text-2xl font-bold">{summary.total}</p></CardContent></Card><Card><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-zinc-500">Pending Action</p><p className="text-2xl font-bold">{summary.pending}</p></div><Clock3 className="text-amber-600"/></CardContent></Card><Card><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-zinc-500">Approved</p><p className="text-2xl font-bold">{summary.approved}</p></div><CheckCircle2 className="text-emerald-600"/></CardContent></Card></div>
  <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-zinc-50 text-left"><tr><th className="p-4">Laboratory</th><th>Equipment</th><th>Schedule</th><th>Status</th><th className="p-4">Actions</th></tr></thead><tbody>{bookings.data.map(b=><tr key={b.id} className="border-t"><td className="p-4 font-medium">{b.laboratory.code}</td><td>{b.items.map(i=>`${i.equipment.name} × ${i.quantity}`).join(', ')}</td><td>{new Date(b.start_time).toLocaleString()}</td><td className="capitalize">{b.status.replaceAll('_',' ')}</td><td className="p-4"><Button size="sm" variant="ghost" asChild><Link href={route('bookings.show',b.id)}>View</Link></Button>{canApproveBooking(b)&&<Button size="sm" onClick={()=>action(b.id,'approve')}>Approve</Button>}{canRejectBooking(b)&&<Button size="sm" variant="ghost" onClick={()=>reject(b.id)}>Reject</Button>}{b.user_id===currentUserId&&b.status==='pending_supervisor'&&<Button size="sm" variant="outline" onClick={()=>edit(b)}>Edit</Button>}{b.user_id===currentUserId&&['pending_supervisor','pending_admin'].includes(b.status)&&<Button size="sm" variant="outline" onClick={()=>action(b.id,'cancel')}>Cancel</Button>}</td></tr>)}</tbody></table></CardContent></Card>
  <Card><CardContent className="p-5"><div className="mb-3 flex items-center gap-2 font-semibold"><CalendarDays className="h-4 w-4 text-indigo-600"/>Upcoming Schedule</div>{bookings.data.length ? <div className="space-y-2">{bookings.data.slice(0,5).map(b=><div key={b.id} className="flex items-center justify-between rounded-lg bg-zinc-50 p-3"><span><b>{b.laboratory.code}</b> · {b.items.map(i=>i.equipment.name).join(', ')}</span><span className="text-xs text-zinc-500">{new Date(b.start_time).toLocaleString()}</span></div>)}</div> : <p className="text-sm text-zinc-500">No bookings to show in the schedule.</p>}</CardContent></Card>
 </div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{editing?'Edit Booking':'New Booking'}</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-3"><Label>Laboratory</Label><Select value={data.laboratory_id} onValueChange={v=>setData('laboratory_id',v)}><SelectTrigger><SelectValue placeholder="Select laboratory"/></SelectTrigger><SelectContent>{laboratories.map(l=><SelectItem key={l.id} value={String(l.id)}>{l.code} — {l.name}</SelectItem>)}</SelectContent></Select><Label>Supervisor</Label><Select value={data.supervisor_id} onValueChange={v=>setData('supervisor_id',v)}><SelectTrigger><SelectValue placeholder="Select supervisor"/></SelectTrigger><SelectContent>{supervisors.map(s=><SelectItem key={s.id} value={String(s.id)}>{s.name}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-2 gap-3"><Input type="datetime-local" value={data.start_time} onChange={e=>setData('start_time',e.target.value)}/><Input type="datetime-local" value={data.end_time} onChange={e=>setData('end_time',e.target.value)}/></div>{data.items.map((item,i)=><div key={i} className="grid grid-cols-[1fr_90px] gap-2"><Select value={item.equipment_inventory_item_id} onValueChange={v=>setData('items',data.items.map((x,n)=>n===i?{...x,equipment_inventory_item_id:v}:x))}><SelectTrigger><SelectValue placeholder="Select equipment"/></SelectTrigger><SelectContent>{selectable.map(e=><SelectItem key={e.id} value={String(e.id)}>{e.name} ({e.quantity} {e.unit_type})</SelectItem>)}</SelectContent></Select><Input type="number" min="1" value={item.quantity} onChange={e=>setData('items',data.items.map((x,n)=>n===i?{...x,quantity:Number(e.target.value)}:x))}/></div>)}<Button type="button" variant="outline" onClick={()=>setData('items',[...data.items,{equipment_inventory_item_id:'',quantity:1}])}>Add Equipment</Button><Textarea placeholder="Purpose" value={data.purpose} onChange={e=>setData('purpose',e.target.value)}/><div className="flex gap-2"><Checkbox checked={data.safety_declared} onCheckedChange={v=>setData('safety_declared',v===true)}/><Label>I confirm all safety requirements.</Label></div><DialogFooter><Button type="submit" disabled={processing}>{editing?'Save Changes':'Submit Booking'}</Button></DialogFooter></form></DialogContent></Dialog></AuthenticatedLayout>;
}
