import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/ui/card';
import { Textarea } from '@/Components/ui/textarea';

export default function Show({ booking, canApprove, canReject }: { booking: any; canApprove: boolean; canReject: boolean }) {
    const [showRejectForm, setShowRejectForm] = useState(false);
    const [rejectionReason, setRejectionReason] = useState('');
    const statusLabel = booking.status === 'pending_admin' ? 'Pending Assistant Engineer' : booking.status.replaceAll('_', ' ');
    const bookingReference = `FTKIP-BK-${String(booking.id).padStart(6, '0')}`;
    const approve = () => { if (window.confirm('Approve this booking request?')) router.patch(route('bookings.update', booking.id), { action: 'approve' }); };
    const reject = () => { if (rejectionReason.trim()) router.patch(route('bookings.update', booking.id), { action: 'reject', rejection_reason: rejectionReason }); };

    return <AuthenticatedLayout header={<div><h2 className="text-2xl font-bold">Booking Details</h2><p className="text-sm text-zinc-500">Booking Reference: {bookingReference} · {statusLabel}</p></div>}><Head title="Booking Details" /><div className="mx-auto max-w-4xl space-y-6 p-6">
        <div className="flex flex-wrap items-center justify-between gap-3"><Button variant="outline" asChild><Link href={route('bookings.index')}>Back to Bookings</Link></Button>{(canApprove || canReject) && <div className="flex items-center gap-2"><span className="text-sm text-zinc-500">Action required</span>{canReject && <Button variant="outline" className="border-rose-200 text-rose-600 hover:bg-rose-50 hover:text-rose-700" onClick={() => setShowRejectForm(true)}>Reject</Button>}{canApprove && <Button className="bg-indigo-600 hover:bg-indigo-700" onClick={approve}>Approve</Button>}</div>}</div>
        {showRejectForm && <Card className="border-rose-200 bg-rose-50/40 dark:border-rose-900 dark:bg-rose-950/10"><CardHeader><CardTitle className="text-rose-700 dark:text-rose-300">Reject Booking Request</CardTitle><CardDescription>Please provide a clear reason. The requester will receive this message.</CardDescription></CardHeader><CardContent className="space-y-3"><Textarea value={rejectionReason} onChange={(event) => setRejectionReason(event.target.value)} placeholder="Explain why this booking cannot be approved..." className="min-h-24 bg-white dark:bg-zinc-950" autoFocus /><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => { setShowRejectForm(false); setRejectionReason(''); }}>Cancel</Button><Button className="bg-rose-600 hover:bg-rose-700" disabled={!rejectionReason.trim()} onClick={reject}>Confirm Rejection</Button></div></CardContent></Card>}
        <div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Booking Information</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Laboratory:</b> {booking.laboratory.code} — {booking.laboratory.name}</p><p><b>Location:</b> {booking.laboratory.location}</p><p><b>Start:</b> {new Date(booking.start_time).toLocaleString()}</p><p><b>End:</b> {new Date(booking.end_time).toLocaleString()}</p><p><b>Status:</b> <span className="capitalize">{statusLabel}</span></p></CardContent></Card><Card><CardHeader><CardTitle>People & Purpose</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><b>Requested by:</b> {booking.user.name}</p><p><b>Supervisor:</b> {booking.supervisor.name}</p><p><b>Purpose:</b></p><p className="rounded-lg bg-zinc-50 p-3 text-zinc-600">{booking.purpose}</p>{booking.rejection_reason && <p className="text-rose-600"><b>Rejection reason:</b> {booking.rejection_reason}</p>}</CardContent></Card></div>
        <Card><CardHeader><CardTitle>Requested Equipment</CardTitle><CardDescription>Equipment and quantities included in this request.</CardDescription></CardHeader><CardContent className="space-y-2">{booking.items.map((item: any) => <div key={item.id} className="flex items-center justify-between rounded-lg border p-3"><span>{item.equipment.name}</span><span className="font-semibold">{item.quantity} {item.equipment.unit_type}</span></div>)}</CardContent></Card>
    </div></AuthenticatedLayout>;
}
